# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- powershell: |
      $environmentFile = "environment.prod.ts"
      (Get-Content $environmentFile).replace("-measurement-id-", "${env:TESTVARNAME}") | Set-Content $environmentFile
      echo start---123
      echo my var: ${env:TESTVARNAME}
      echo start---123
  workingDirectory: 'frontend/src/environments'
  displayName: 'Set Variables'
    
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo ${env:TESTVARNAME}
    echo 123
  displayName: 'Run a multi-line script'
