trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build and Push'
    inputs:
      containerRegistry: 'docker-registry-connection'
      repository: CiContainerRepo
      Dockerfile: frontend/.docker/Dockerfile
      buildContext: frontend/inventory
      tags: turnik-app-latest
