trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - powershell: |
      $environmentFile = "environment.prod.ts"
      (Get-Content $environmentFile).replace("-measurement-id-", "$(GOOGLETRACKINGCODE)") | Set-Content $environmentFile
      (Get-Content $environmentFile).replace("-access-token-", "$(MAPBOXACCESSTOKEN)") | Set-Content $environmentFile
    workingDirectory: 'frontend/src/environments'
    displayName: 'Set Variables'

  - script: |
      npm install -g @angular/cli
      npm install
      npm run build:prod
    workingDirectory: frontend
    displayName: 'npm install and build'

  - powershell: |
      $indexHtml = "index.html"
      (Get-Content $indexHtml).replace("-build.id-", "$(Build.BuildNumber)") | Set-Content $indexHtml
      (Get-Content $indexHtml).replace("-branch.name-", "$(Build.SourceBranchName)") | Set-Content $indexHtml
    workingDirectory: 'frontend/dist/turnik-app/browser'
    displayName: 'Build counters'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: 'frontend/dist/turnik-app/browser'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
