trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build and Push'
    inputs:
      containerRegistry: 'docker-connection'
      repository: CiContainerRepo
      Dockerfile: backend/.docker/Dockerfile
      buildContext: backend
      tags: latest